config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions'},path_names: { sign_in: 'login', sign_up: 'signup' }
           
  get 'home' => 'home#index'
  get '/users/:id', to: 'users#show'

  
  
  root 'home#index'
  resources :bitacoras

end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bitacoras
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


   protected
   		def configure_permitted_parameters
      		devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/bitacoras_controller.rb
class BitacorasController < ApplicationController
before_action :authenticate_user!

	def destroy
		  @bitacora = Bitacora.find(params[:id])
		  @bitacora.destroy

		  redirect_to bitacoras_path
	end

	def index
		@bitacoras = current_user.bitacoras
		@bitacora = Bitacora.new
	end

	def new
		@bitacora = Bitacora.new
	end

	def create 
		@bitacora = Bitacora.new(bitacora_params)
		@bitacora.user = current_user
	if @bitacora.save
		redirect_to bitacoras_path, notice: "bitacora was succesfully created."
	else
		render :new 
	end

	end



private
 def bitacora_params
 	params.require(:bitacora).permit(:name, :provincia, :fecha, :visitas, :acompañantes, :anecdotas)
 end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    super do |resource|
      puts "Crea tu Bitácora #{resource.name}"
     end
  end
end
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])
		render 'users/show'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bitacoras/_form.html.erb
<%= form_for(@bitacora) do |f| %>
  <% if @bitacora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bitacora.errors.count, "error") %> prohibited this bitacora from being saved:</h2>

      <ul>
      <% @bitacora.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
          
          <h2 class = "encimaNewBitacora"><b>Nueva Bitácora</b></h2>

  <section class ="bitacoraBackground">
   <article class = "newBitacora">

    <form class="form-horizontal" role="form">

      <div class="form-group input-group">
            <%= f.label :Título %>
            <%= f.text_field :name, :class => "form-control", :placeholder =>"Escribe el titulo" %>
          </div>
          <div class="form-group input-group">
            <%= f.label :provincia %>
            <%= f.text_field :provincia, :class => "form-control", :placeholder =>"Escribe la provincia" %>
          </div>
          <div class="form-group input-group">
            <%= f.label :fecha %>
            <%= f.text_field :fecha, :class => "form-control", :placeholder =>"Escribe la fecha" %>
          </div>
          <div class="form-group input-group">
            <%= f.label :planes %>
            <%= f.text_field :visitas, :class => "form-control", :placeholder =>"Escribe tus planes" %>
          </div>
          <div class="form-group input-group">
            <%= f.label :acompañantes %>
            <%= f.text_field :acompañantes, :class => "form-control", :placeholder =>"Escribe tus acompañantes" %>
          </div>
           <div class="form-group input-group">
            <%= f.label :anecdotas %>
            <%= f.text_field :anecdotas, :class => "form-control", :placeholder =>"Escribe las anecdotas" %>
          </div>

          <div class="actions ">
            <%= f.submit "Crea tu Bitácora" ,:class => "btn btn-success", :style => "font-size: 20px; margin-top: 15px" %>
          </div>
        <% end %>


  
<div class = "pie">

</div>


  </article>

</section>



<div class = "pie">

</div>

app/views/bitacoras/index.html.erb
<header class="navigation">
	<h1 class="logo">Bitácora de viajes</h1>
	<nav>
		<ul class= "nav-bar">
			<li><%= link_to 'Crea tu Bitácora', new_bitacora_path, {:style => 'color: #FFFFFF'} %></li>
			
			<% if user_signed_in? %>

			<li class = "hello">Hola, <%= current_user.name %>!</h2></li>
			<li class = "out"><%= link_to 'Salir', destroy_user_session_path, :style => 'color: #FFFFFF', method: :delete  %></li>
			<% else %>
			<li><%= link_to 'Regístrate', new_user_registration_path  %></li>
			<li><%= link_to 'Identificate', new_user_session_path  %></li>
		
			<% end %>							  	
		</ul>
	</nav>
</header>

<div class="bitacoras">

	<% @bitacoras.each do |bitacora| %>
		<article class="bitacora container">
					
			<li class = "list"><b>Nombre:</b> <%= bitacora.name %></li>
			<li class = "list"><b>Fecha:</b> <%= bitacora.fecha %></li>
			<li class = "list"><b>Provincia:</b><%= bitacora.provincia %></li>
			<li class = "list"><b>Visitas:</b> <%= bitacora.visitas %></li>
			<li class = "list"><b>Acompañantes:</b> <%= bitacora.acompañantes %></li>
			<li class = "list"><b>Anécdotas:</b> <%= bitacora.anecdotas %></li>
			

		</article>
		<article class="bitacora-btn">
			<button type="button" class="btn btn-danger letter"><%= link_to 'Eliminar', bitacora_path(bitacora),
		 			method: :delete, data:
		            {confirm: 'Estás seguro?'}
		            %></button>

			<button type="button" class="btn btn-info letter"><%= link_to 'Nueva Bitácora', new_bitacora_path %></button>
			

		</article>
	<% end %>
</div>


	<%= form_for(@bitacora) do |f| %>
	  <% if @bitacora.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@bitacora.errors.count, "error") %> prohibited this bitacora from being saved:</h2>

	      <ul>
	      <% @bitacora.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	
	<section class = "book container">
		
		<form action = "">
		
 			<ul class= "formulario">
			    <div class="form-group input-group">
			    <%= f.label :nombre %>
			    <%= f.text_field :name, :class => "form-control margin-left: 390px" %>
			  </div>
			  <div class="form-group input-group">
			    <%= f.label :provincia %>
			    <%= f.text_field :provincia, :class => "form-control col-xs-3" %>
			  </div>
			  <div class="form-group input-group">
			    <%= f.label :fecha %>
			    <%= f.text_field :fecha, :class => "form-control" %>
			  </div>
			  <div class="form-group input-group">
			    <%= f.label :visitas %>
			    <%= f.text_field :visitas, :class => "form-control" %>
			  </div>
			  <div class="form-group input-group">
			    <%= f.label :acompañantes %>
			    <%= f.text_field :acompañantes,:class => "form-control" %>
			  </div>
			   <div class="form-group input-group">
			    <%= f.label :anécdotas %>
			    <%= f.text_field :anecdotas, :class => "form-control" %>
			  </div>

	  		
	    	<%= f.submit "Crea tu Bitácora", :class => "btn btn-success", :style => "font-size: 15px" %>
	  		</div>

				<% end %>
		</ul>
	</form>


	</section>

	
</div>

</div>



<footer class = "footer">
	<section class="container">
		<article id = "social">
 			<ul class = "icons">
 				<li><div class = "facebook"></li>
 				<li><div class = "twitter"></li>
 				<li><div class = "instagram"></li>
 				<li><div class = "github"></li>
 			</ul>
 		</article>
		
		<article id = "contact">
			<h3><b>Contacta</b></h3>
			<p>Avenida de Brasil, 55</p>
			<p>Teléfono 91 554 39 75</p>
			<p>Email patri@gmail.com</p>


		</article>
		<div class= "copyRight container">
			<p>2014 Crea tu Bitácora</p>
		</div>
	</section>
	

</footer>

app/views/bitacoras/new.html.erb
					


<%= render 'form' %>

app/views/home/index.html.erb
<body>
	<header class="navigation">
		<h1 class="logo">Bitácora de viajes</h1>
		<nav>
			<ul class= "nav-bar">
			<li ><%= link_to 'Inicio', home_path, {:style => 'color: #FFFFFF'}%></li>
			
				
				<% if user_signed_in? %>
				<li><%= link_to 'Crea tu Bitácora', new_bitacora_path, {:style => 'color: #FFFFFF'} %></li>
				<li><%= link_to 'Salir', destroy_user_session_path, :style => 'color: #FFFFFF', method: :delete %></li>
				<% else %>
				<li><%= link_to 'Regístrate', new_user_registration_path, {:style => 'color: #FFFFFF'} %></li>
				<li><%= link_to 'Identificate', new_user_session_path, {:style => 'color: #FFFFFF'} %></li>

				<% end %>							  	
			</ul>
		</nav>
	</header>

	<section class="background">
		<h2> Mi bitácora </h2>
	</section>

	<section class="info">
		<article class="gif"></article>
		<article class="texto">Alguna vez has querido recordar todos tus viajes?
		<br> <a href="modalBlack">¿Estás preparado para crear tu bitácora?
		</br>
		<span>Sigue leyendo!</span></a></article>
		
	</section>

	<section class="container">
		<article class="item">
			<div class="city col-md-6 col-sm-6 col-lg-6">
				<div class = "info1">
					<p id = "headline1">Ciudad</p>
				</div>
			</div>
			<div class = "title1 col-md-6 col-sm-6 col-lg-6">
				<h4><b>Elige tu ciudad</b></h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas pellentesque sapien nunc, in lacinia ipsum gravida ac. Curabitur sagittis, ex id tincidunt cursus, ipsum neque vulputate est, in fermentum nisl diam eu massa. Donec cursus malesuada sem, eu maximus sapien blandit eget. Praesent sit amet ex eget ante pharetra sagittis. </p>
			</div>
		</article>
			
	</section>
	<section class="container margin-cnt">
		<article class="item">
			<div class="calendar col-md-6 col-sm-6 col-lg-6">
				<div class = "info2">
					<p id = "headline2">Calendario</p>
				</div>
			</div>
			<div class = "title2 col-md-6 col-sm-6 col-lg-6">
				<h4><b>Elige la fecha</b></h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi nulla, quo, maxime facilis a consequuntur? Velit dignissimos earum aspernatur, iure voluptatem minima eius repudiandae, assumenda consectetur eveniet provident quos excepturiEtiam fringilla accumsan arcu. Maecenas eleifend elit at nisl luctus, vel hendrerit massa bibendum. Etiam pretium, quam non aliquet commodo, mi massa venenatis lacus, sit amet venenatis risus ex et lorem. .</p>
			
		</article>
	</section>

	<section class="container margin-cnt">
		<article class="item">
			<div class="plans">
				<div class = "info3">
				<p id = "headline3">Planes</p>
				</div>
			</div>
			<div class = "title3">
				<h4><b>Elige tus planes</b></h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Temporibus modi veritatis dolorum harum explicabo reprehenderit enim, dolorem, nam tempora nemo, doloribus animi. Tempore nihil dolorem delectus nostrum sed error fuga? Etiam fringilla accumsan arcu. Maecenas eleifend elit at nisl luctus, vel hendrerit massa bibendum. Etiam pretium, quam non aliquet commodo, mi massa venenatis lacus, sit amet venenatis risus ex et lorem. Maecenas nisl purus, gravida at dui sit amet, volutpat laoreet mauris. Aenean congue feugiat erat vel pretium. Suspendisse ultricies ornare nunc quis accumsan.</p>
				</div>
		</article>
	</section>

<section class="container margin-cnt btn-cnt">
	<button class="btn btn-lg btn-default boton" type="submit">
	<%= link_to 'Crea tu Bitácora', new_bitacora_path %></button>
</section>




<footer class = "footer">
	<section class="container">
		<article id = "social">
 			<ul class = "icons">
 				<li><div class = "facebook"></li>
 				<li><div class = "twitter"></li>
 				<li><div class = "instagram"></li>
 				<li><div class = "github"></li>
 			</ul>
 		</article>
		
		<article id = "contact">
			<h3><b>Contacta</b></h3>
			<p>Avenida de Brasil, 55</p>
			<p>Teléfono 91 554 39 75</p>
			<p>Email patri@gmail.com</p>


		</article>
		<div class= "copyRight container">
			<p>2014 Crea tu Bitácora</p>
		</div>
	</section>
	

</footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiBitacora</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<% if user_signed_in? %>
	<h2>Welcome <%= current_user.name %>!</h2>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
<h2>Nobody logued in</h2>
<% end %>

	